dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2021.1.19=h06a4308_1
  - certifi=2020.12.5=py36h5fab9bb_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - dataclasses=0.8=pyh787bdff_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h7ca028e_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2020.2=254
  - jpeg=9b=0
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libiconv=1.14=0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=he1b5a44_3
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36h8c4c3a4_2
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.2.0=py36h7c3b610_1
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - ninja=1.7.2=0
  - olefile=0.44=py36_0
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.1.2=py36he98fc37_0
  - pip=21.0.1=pyhd8ed1ab_0
  - python=3.6.13=hdb3f193_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.8.1=py3.6_cuda10.1_cudnn7.6.3_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.10.0=py36_0
  - sqlite=3.35.2=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.8.1=py36
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.6=0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.12.0
    - cachetools==4.2.1
    - chardet==4.0.0
    - cycler==0.10.0
    - cython==0.29.22
    - future==0.18.2
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.3
    - grpcio==1.36.1
    - idna==2.10
    - importlib-metadata==3.9.1
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - torch==1.7.0
    - torchvision==0.8.1
    - tqdm==4.59.0
    - urllib3==1.26.4
    - werkzeug==1.0.1
    - zipp==3.4.1
